import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const helveticaNeueLight = localFont({
  src: [
    {
      path: "./assets/fonts/SFUIText-Heavy.woff",
      weight: "800",
    },
    {
      path: "./assets/fonts/SFUIText-Bold.woff",
      weight: "700",
    },
    {
      path: "./assets/fonts/SFUIText-Regular.woff",
      weight: "500",
    },
    {
      path: "./assets/fonts/SFUIText-Light.woff",
      weight: "400",
    },
  ],

  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "Kludy",
  description: "Generated by create next app :)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaNeueLight.className}`}>{children}</body>
    </html>
  );
}
